### ISSUE TITLE
cannot be used twice on one page,

### ISSUE THREAD

**Issue by dart200** [alexus37/react-google-streetview#2]
due to loading the google.maps script twice. google does not like that, and the scripts bug out.

<img width="1099" alt="Screen Shot 2020-01-18 at 6 13 21 PM" src="https://user-images.githubusercontent.com/565335/72662145-83a0ba00-3a1e-11ea-87c6-ea795144800c.png">

(the white box should be showing one of the street view instances)

i dunno if this is something you want to fix, or perhaps there is some way around this i'm not aware of? but for my use case, it seems to be an issue.

**Comment by alexus37** [comment]
Thanks for reporting this. I will start looking into that next week!

**Comment by dart200** [comment]
cool, thanks.

some more thoughts: when i was initially exploring with one instance, i was also using the gmaps script outside of streetview for some distance calculations. i ran into the same problem, and solved it by setting a looping timeout to check if streetview had loaded it:

```javascript
const checkGMapsAPILoaded = handleLoad => () => {
  if (!window.google) {
    setTimeout(checkGMapsAPILoaded(handleLoad), 100);
  } else {
    handleLoad();
  }
};
```

but i feel like there really ought be to be a better way of handling multiple components using the same 3rd party scripts.

**Comment by alexus37** [comment]
This is fixed now. If you want to use multiple instances of google streetview you have to load the google maps JavaScript Api yourself and provide it as a property to the react component. Check out the demo [here](https://alexus37.github.io/react-google-streetview/)

**Comment by dart200** [comment]
sounds good, thanks!

**Comment by dart200** [comment]
hey man, slight issue: the fix does not seem to have made it into the minified code i get from npm.

**Comment by alexus37** [comment]
Ah sorry, should be published now!

**Comment by dart200** [comment]
works now, thanks again!
