### ISSUE TITLE
Can this work in React-Native?

### ISSUE THREAD

**Issue by disrae** [alexus37/react-google-streetview#3]
Sorry for the issue, 

Just want to confirm that this can't work in react-native.

**Comment by alexus37** [comment]
To be honest I am not sure. I haven't tried it. I this [thread](https://stackoverflow.com/questions/49123840/can-i-use-reactjs-library-in-react-native) they mention that it is not possible if the component is using DOM functionality. I would recommend to go with a lib developed for this purpose like https://www.npmjs.com/package/react-native-streetview

**Comment by disrae** [comment]
Thanks for the quick answer! My issue is I need the event listeners for change of pov. Thanks though!
